### ISSUE TITLE
Does not build with rustc 1.8.0

### ISSUE THREAD

**Issue by nagisa** [serde-rs/json#198]
serde-json 0.8.3 -> 0.8.5 begun failing to build on older versions of rust.

```
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:219:34: 226:22 error: if and else have incompatible types:
 expected `&[u8]`,
    found `&'s mut collections::vec::Vec<u8>`
(values differ in mutability) [E0308]
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:219                     let string = if scratch.is_empty() {
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:220                         // Fast path: return a slice of the raw JSON without any
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:221                         // copying.
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:222                         &self.slice[start..self.index]
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:223                     } else {
/home/nagisa/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_json-0.8.5/src/read.rs:224                         scratch.extend_from_slice(&self.slice[start .. self.index]);
                                                                                              ...
```

Lack of smarts in 1.8.0 could be easily fixed by adding a `&scratch[..]` or somesuch onto scratch. 1.10.0 builds fine.

**Comment by dtolnay** [comment]
Can you explain a bit more about your use case? How do you end up pinned to a 9-month-old compiler but using 1-day-old crates? We support old compilers in serde and serde_json but not that old.

As far as I can tell, our options are:

- Never use new compiler features beyond some particular Rust release, say 1.0.0 or 1.8.0. If this applies only to us, why? If this applies to the entire Rust library ecosystem, then why bother continuing to develop the compiler at all if nobody can use new things?
- Use new compiler features but put them behind a cfg, preserving the ability to use old compilers without the cfg. Eventually people need to enable dozens of cfgs to get anything done.
- Use new compiler features after they have been stable for a reasonable amount of time, say 3 releases. Run continuous integration tests against those 3 old releases. This is what we do now.

Do you think one of the other options is better than what we currently do?

Serde and serde_json both support Rust 1.8.0 - try using serde 0.7 and serde_json 0.7.

**Comment by nagisa** [comment]
> Can you explain a bit more about your use case?

I usually have a particular version of compiler pinned for CI of my crates (to run along with nightly and stable), to ensure I do not regress people who do not upgrade for some reason (e.g. never run `rustup update`). I do not try particularly hard to maintain compatibility (i.e. if I want to use some feature, I just bump the version of rustc that CI uses), but cases like the one I reported here is something that can be trivially resolved to keep crates compatible and have almost no cost.

> How do you end up pinned to a 9-month-old compiler but using 1-day-old crates?

So my crate has `0.8` as a bound and pushing to the CI today ended up pulling the new version… which failed to compile.

---

I’ve bumped the pinned version on CI to 1.10 now, so I’m not particularly affected anymore. Please consider this issue report more of a note that the crate broke and could easily be fixed, rather than a bug or feature request.

Its for you to choose if you want to act on it.

**Comment by dtolnay** [comment]
Thanks for the explanation. I agree in this case it is easy to support so I fixed it in df906b07b104a0098453aa3f819e5df55bded76f and released the fix in serde_json 0.8.6.
